### ISSUE TITLE
neueste Version bricht mit node 0.10/0.12 ?!

### ISSUE THREAD

**Issue by Apollon77** [soef/ioBroker.samsung#6]
Neueste Version schlägt beim testing fehl, weil "const" verwendet wird und damit es nur ab node 4.x tut.
Adapter sollte das in der Doku haben bzw. könnte halt fr User zu Problemen führen die updaten wollen ...

**Comment by soef** [comment]
Behoben. Ich - für Node Versionen kleiner 4.0.0 - die Unterstützung der 2016er Geräte entfernt.
